## 03 Classification Homework/Project

In [77]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mutual_info_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score
from sklearn.inspection import permutation_importance

### Download data and read it

In [2]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/course_lead_scoring.csv'

In [3]:
!wget $data

--2026-07-22 03:36:41--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/course_lead_scoring.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 80876 (79K) [text/plain]
Saving to: ‘course_lead_scoring.csv.1’

course_lead_scoring 100%[===================>]  78.98K  --.-KB/s    in 0.001s

2026-07-22 03:36:41 (55.6 MB/s) - ‘course_lead_scoring.csv.1’ saved [80876/80876]

In [4]:
df = pd.read_csv(data)

In [5]:
df.shape

(1462, 9)

In [6]:
df.head()

,lead_source,industry,number_of_courses_viewed,annual_income,employment_status,location,interaction_count,lead_score,converted
0,paid_ads,NaN,1,79450.0,unemployed,south_america,4,0.94,1
1,social_media,retail,1,46992.0,employed,south_america,1,0.80,0
2,events,healthcare,5,78796.0,unemployed,australia,3,0.69,1
3,paid_ads,retail,2,83843.0,NaN,australia,1,0.87,0
4,referral,education,3,85012.0,self_employed,europe,3,0.62,1

In [7]:
df.dtypes

lead_source                     str
industry                        str
number_of_courses_viewed      int64
annual_income               float64
employment_status               str
location                        str
interaction_count             int64
lead_score                  float64
converted                     int64
dtype: object

### Data Preparation

In [8]:
X = df.drop(columns = 'converted')

In [9]:
y = df.converted

In [10]:
#check missing values for each features
X.isnull().sum()

lead_source                 128
industry                    134
number_of_courses_viewed      0
annual_income               181
employment_status           100
location                     63
interaction_count             0
lead_score                    0
dtype: int64

In [11]:
categorical_cols = X.dtypes.index[X.dtypes =='str']

In [12]:
categorical_cols

Index(['lead_source', 'industry', 'employment_status', 'location'], dtype='str')

In [13]:
numerical_cols = X.columns.difference(categorical_cols)

In [14]:
numerical_cols

Index(['annual_income', 'interaction_count', 'lead_score',
       'number_of_courses_viewed'],
      dtype='str')

In [15]:
X[categorical_cols] = X[categorical_cols].fillna('NA')

In [16]:
X[numerical_cols] = X[numerical_cols].fillna(0)

In [17]:
X.isnull().sum()

lead_source                 0
industry                    0
number_of_courses_viewed    0
annual_income               0
employment_status           0
location                    0
interaction_count           0
lead_score                  0
dtype: int64

In [18]:
X.dtypes

lead_source                     str
industry                        str
number_of_courses_viewed      int64
annual_income               float64
employment_status               str
location                        str
interaction_count             int64
lead_score                  float64
dtype: object

In [19]:
X.industry.value_counts()

industry
retail           203
finance          200
other            198
healthcare       187
education        187
technology       179
manufacturing    174
NA               134
Name: count, dtype: int64

### Question 1: retail

In [20]:
X[numerical_cols].corr()

,annual_income,interaction_count,lead_score,number_of_courses_viewed
annual_income,1.000000,0.027036,0.015610,0.009770
interaction_count,0.027036,1.000000,0.009888,-0.023565
lead_score,0.015610,0.009888,1.000000,-0.004879
number_of_courses_viewed,0.009770,-0.023565,-0.004879,1.000000

### Question 2: 0.027036 interaction_count  & annual_income

In [21]:
# Step 1: Split into Train+Val (80%) and Test (20%)
X_train_val, X_test, y_train_val, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42, stratify=y
)

# Step 2: Split Train+Val into final Train (75% of 80% = 60%) and Val (25% of 80% = 20%)
X_train, X_val, y_train, y_val = train_test_split(
    X_train_val, y_train_val, test_size=0.25, random_state=42, stratify=y_train_val
)

In [22]:
X_train.shape,  X_val.shape, X_test.shape

((876, 8), (293, 8), (293, 8))

In [23]:
X.columns

Index(['lead_source', 'industry', 'number_of_courses_viewed', 'annual_income',
       'employment_status', 'location', 'interaction_count', 'lead_score'],
      dtype='str')

In [24]:
X.dtypes

lead_source                     str
industry                        str
number_of_courses_viewed      int64
annual_income               float64
employment_status               str
location                        str
interaction_count             int64
lead_score                  float64
dtype: object

In [25]:
for col in categorical_cols:
    mi = mutual_info_score(X_train[col], y_train)
    print (f'mi score between {col} and response variable is {mi}')

mi score between lead_source and response variable is 0.027718699139711492
mi score between industry and response variable is 0.005958887591320947
mi score between employment_status and response variable is 0.007695750218801714
mi score between location and response variable is 0.0014310098448050215

###  Question 3: lead_scource

In [42]:
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore', drop='first')

In [43]:
preprocessor = ColumnTransformer(
    transformers=[
        ('cat_processing', encoder, categorical_cols),
        ('num_processing', 'passthrough', numerical_cols) # 'passthrough' leaves numbers untouched
    ]
)

In [44]:
lr =  LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)

In [45]:
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', lr)
])

In [46]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat_processing',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False),
                                                  Index(['lead_source', 'industry', 'employment_status', 'location'], dtype='str')),
                                                 ('num_processing',
                                                  'passthrough',
                                                  Index(['annual_income', 'interaction_count', 'lead_score',
       'number_of_courses_viewed'],
      dtype='str'))])),
                ('classifier',
                 LogisticRegression(max_iter=1000, random_state=42,
                                    solver='liblinear'))])

In [69]:
val_predicitions = pipeline.predict(X_val)

In [71]:
val_predicitions

array([1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1])

In [75]:
accuracy = round(accuracy_score(val_predicitions, y_val),2)

In [76]:
accuracy

0.73

### Question 4 0.74

In [ ]:
### Need further understanding of permutation importance
import pandas as pd
from sklearn.inspection import permutation_importance

# 1. Run the permutation importance tool
# Pass your trained pipeline, validation features, and validation targets
result = permutation_importance(
    pipeline,          # Your entire trained Pipeline
    X_val,             # Validation features (raw DataFrame before encoding)
    y_val,             # Validation targets
    n_repeats=10,      # Number of times to shuffle each feature
    random_state=42,   # Ensures consistent, reproducible results
    scoring='accuracy' # The metric used to evaluate performance drop
)

# 2. Extract results into a clean Pandas DataFrame
importance_df = pd.DataFrame({
    'Feature': X_val.columns,
    'Importance_Mean': result.importances_mean,
    'Importance_Std': result.importances_std
}).sort_values(by='Importance_Mean', ascending=False)

print(importance_df)